server:
  port: 6500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    appname: orderservice
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: pass@word1
    driverClassName: com.mysql.jdbc.Driver
    initialize : true
    maximum-pool-size: 30
  cloud:
    application:
      name: orderservice