server:
  port: 5000

  instance:
    appname: orderservice
spring:
  datasource:
    url: jdbc:mysql://testdb.cpopvifsuac5.ap-south-1.rds.amazonaws.com:3306/testdb
    username: root
    password: password$$
    driverClassName: com.mysql.jdbc.Driver
    initialize : true
    maximum-pool-size: 30
  cloud:
    application:
      name: orderservice